script: mvn verify javadoc:javadoc coveralls:report -Pcoverage
install: true
branches:
  only:
  - master
  - /\d\.0\.0-RC/
language: java
jdk:
  - openjdk8
  - openjdk7
cache:
  directories:
  - '$HOME/.m2/repository'
sudo: false
dist: trusty
